services:
  - name:chatMultiUsers
    type: web
    buildCommand: |
      cd client && npm install
      cd server && npm install
    startCommand: |
      cd client && npm run dev 
      cd ../server && node index.js